import { relationKind } from '../evaluator/contracts.js';
import { t } from '../i18n/index.js';
import { relationTone } from './setupExportMap.js';
import { toolScope, discoveredWikis } from './graphModel.js';

const safeHex = (value, fallback) => /^#[\da-f]{3}(?:[\da-f]{3})?$/i.test(value || '') ? value : fallback;
const blend = (first, second, amount) => {
  const expand = value => value.length === 4 ? '#' + [...value.slice(1)].map(char => char + char).join('') : value;
  const a = expand(first), b = expand(second);
  return '#' + [1, 3, 5].map(index => Math.round(parseInt(a.slice(index, index + 2), 16) * (1 - amount) + parseInt(b.slice(index, index + 2), 16) * amount).toString(16).padStart(2, '0')).join('');
};

export function createSetupHtml({ report, model, mapSvg, palette, bg, ink, language, includePaths, kindLabel, escapeMarkup }) {
  const esc = escapeMarkup;
  const components = report.components || [];
  const relationships = report.relationships || [];
  const componentAnchor = new Map(components.map((item, index) => [item.id, 'component-' + index]));
  const mapped = new Set([...model.tools, ...model.elements].map(item => item.id));
  const sections = [
    { name: t('Tool AI'), items: model.tools, tone: safeHex(palette.centralTool?.background, '#e7f7c9') },
    ...model.groups.map(group => ({ name: t(group.name), items: group.items, tone: safeHex(palette.categories?.[group.category], '#94a3b8') })),
    { name: t('Componenti fuori mappa'), items: components.filter(item => !mapped.has(item.id)), tone: '#94a3b8' }
  ];
  const surface = blend(bg, ink, 0.07);
  const border = blend(bg, ink, 0.2);
  const muted = blend(bg, ink, 0.64);
  const accent = ink === '#000000' ? '#167da8' : '#22d3ee';
  const css = [
    ':root{color-scheme:', ink === '#000000' ? 'light' : 'dark', ';--bg:', bg, ';--ink:', ink, ';--surface:', surface, ';--border:', border, ';--muted:', muted, ';--accent:', accent, '}',
    '*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg);color:var(--ink);font:14px/1.6 "JetBrains Mono","Cascadia Code",Consolas,ui-monospace,monospace}a{color:inherit;text-underline-offset:3px}a:hover{color:var(--accent)}a:focus-visible,summary:focus-visible{outline:2px solid var(--accent);outline-offset:3px}h1,h2,h3,p,dl{margin-top:0}h1,h2,h3{line-height:1.25;overflow-wrap:anywhere}p,dd,code{overflow-wrap:anywhere}code{font:inherit}summary{cursor:pointer}summary::marker{color:var(--accent)}',
    '.skip{position:absolute;left:-9999px;top:8px;z-index:10;padding:8px 12px;background:var(--surface)}.skip:focus{left:8px}.topbar{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:12px clamp(18px,4vw,48px);border-bottom:1px solid var(--border);background:var(--surface)}.brand{font-size:11px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;white-space:nowrap}.brand span{color:var(--accent)}.topbar nav{display:flex;gap:20px;flex-wrap:wrap}.topbar nav a{text-decoration:none;font-size:12px;color:var(--muted)}.topbar nav a:hover,.topbar nav a:focus{color:var(--accent)}.offline{font-size:11px;color:var(--muted);white-space:nowrap}',
    'main{max-width:1600px;margin:auto;padding:clamp(20px,3vw,44px)}.eyebrow{font-size:10px;font-weight:700;letter-spacing:.16em;text-transform:uppercase;color:var(--accent)}.intro{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:24px;align-items:end;margin-bottom:28px}.intro h1{font-size:clamp(26px,3vw,42px);letter-spacing:-.04em;margin-bottom:6px}.stats{display:flex;gap:28px;margin:0}.stats div{min-width:70px;border-left:1px solid var(--border);padding-left:14px}.stats dt{font-size:10px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.stats dd{font-size:24px;font-weight:700;margin:2px 0 0}',
    '.panel{border:1px solid var(--border);background:var(--surface);border-radius:12px;overflow:hidden}.panel-head{display:flex;align-items:center;justify-content:space-between;gap:20px;padding:16px 20px;border-bottom:1px solid var(--border)}.panel-head h2{font-size:15px;margin:0}.panel-head p{margin:0;font-size:11px;color:var(--muted)}.map-frame{overflow:auto;background:var(--bg)}.map-frame svg{display:block;width:100%;min-width:850px;height:auto}.map-frame .hotspot{cursor:pointer}.map-frame .node-plate,.map-frame .node-halo{transition:stroke .18s ease,opacity .18s ease}.map-frame .hotspot:hover .node-plate,.map-frame .hotspot:focus-visible .node-plate{stroke:var(--accent);stroke-width:2}.map-frame .hotspot:hover .node-halo,.map-frame .hotspot:focus-visible .node-halo{opacity:.2}.map-frame .hotspot:focus-visible{outline:none}.legend{display:flex;flex-wrap:wrap;gap:8px 22px;padding:12px 20px;border-top:1px solid var(--border)}.legend-item{display:inline-flex;align-items:center;gap:9px;font-size:11px;color:var(--muted)}.legend-item svg{width:30px;height:8px;flex:none}.note{margin:14px 0 0;color:var(--muted);font-size:12px}',
    '.section-head{display:flex;align-items:baseline;justify-content:space-between;gap:16px;margin:48px 0 14px}.section-head h2{font-size:20px;margin:0}.section-head span{font-size:12px;color:var(--muted)}.catalog{display:grid;grid-template-columns:220px minmax(0,1fr);gap:24px}.index{align-self:start;position:sticky;top:16px;padding:14px;border:1px solid var(--border);border-radius:10px;background:var(--surface)}.index h3{font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);margin:0 0 10px}.index a{display:flex;justify-content:space-between;gap:12px;padding:7px 4px;border-top:1px solid var(--border);font-size:11px;text-decoration:none}.index small{color:var(--muted)}.group-list{min-width:0}.group{border:1px solid var(--border);border-left:2px solid var(--tone);border-radius:10px;background:var(--surface);margin-bottom:10px;scroll-margin-top:14px}.group:target{border-color:var(--accent)}.group summary{display:flex;align-items:center;gap:12px;padding:14px 17px;list-style:none}.group summary::-webkit-details-marker{display:none}.group summary:before{content:"+";width:16px;color:var(--accent)}.group[open] summary:before{content:"−"}.swatch{width:10px;height:10px;border-radius:2px;background:var(--tone);flex:none}.group-title{font-weight:700}.group-count{margin-left:auto;color:var(--muted);font-size:11px}.records{border-top:1px solid var(--border)}.record{display:grid;grid-template-columns:minmax(160px,25%) minmax(0,1fr) auto;gap:14px;padding:14px 18px;border-top:1px solid var(--border);scroll-margin-top:16px}.record:first-child{border-top:0}.record:target{background:var(--bg);outline:1px solid var(--accent)}.record h3{font-size:12px;margin:0;border-left:2px solid var(--tone);padding-left:12px}.record h3 small{display:block;font-weight:400;color:var(--muted);margin-top:4px}.record p{font-size:12px;margin:0;color:var(--muted);white-space:pre-wrap}.record .state{align-self:start;font-size:10px;letter-spacing:.04em;color:var(--muted);white-space:nowrap;border:1px solid var(--border);border-radius:99px;padding:3px 8px}.record code{display:block;margin-top:6px;font-size:11px;color:var(--ink)}',
    '.relationship-list{list-style:none;padding:0;margin:0}.relationship-list li{border-top:1px solid var(--border)}.relationship-list li:first-child{border-top:0}.relationship-list details{padding:0 18px}.relationship-list summary{display:flex;gap:12px;align-items:baseline;padding:13px 0;list-style:none}.relationship-list summary::-webkit-details-marker{display:none}.relationship-list summary:before{content:"+";color:var(--accent)}.relationship-list details[open] summary:before{content:"−"}.relationship-list strong{font-size:12px;font-weight:600}.relationship-list .relation-kind{margin-left:auto;white-space:nowrap;font-size:10px;color:var(--muted)}.relationship-list .relation-body{padding:0 0 16px 24px;font-size:12px;color:var(--muted)}.relationship-list .relation-body p{margin:0 0 8px}.relationship-list .relation-body a{color:var(--accent)}.empty{padding:24px;color:var(--muted)}footer{margin:36px 0 0;padding-top:16px;border-top:1px solid var(--border);font-size:11px;color:var(--muted)}',
    '.tool-nav{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0 18px}.tool-nav a,.tool-scope{border:1px solid var(--border);border-radius:9px;background:var(--surface)}.tool-nav a{padding:8px 12px;text-decoration:none;font-size:12px}.tool-nav a:hover,.tool-nav a:focus-visible{border-color:var(--accent)}.tool-scope{padding:18px 20px;margin:12px 0;scroll-margin-top:16px}.tool-scope:target{border-color:var(--accent)}.tool-scope h3{margin:0 0 5px;font-size:17px}.tool-scope p,.wiki-discovery p{margin:0 0 10px;color:var(--muted);font-size:12px}.tool-scope details{border-top:1px solid var(--border);padding:9px 0}.tool-scope summary{font-size:12px}.tool-scope ul,.wiki-discovery ul{display:flex;flex-wrap:wrap;gap:7px 16px;padding:0;margin:9px 0;list-style:none}.tool-scope li,.wiki-discovery li{font-size:11px}.tool-scope li small{display:block;color:var(--muted);font-size:10px}.tool-scope a,.wiki-discovery a{color:var(--accent)}.wiki-discovery{border-left:2px solid var(--accent);padding:12px 16px;margin-top:20px;background:var(--surface)}.wiki-discovery h3{font-size:14px;margin:0 0 6px}',
    '@media(max-width:900px){.intro{grid-template-columns:1fr}.stats{justify-content:flex-start}.catalog{grid-template-columns:1fr}.index{position:static;display:flex;flex-wrap:wrap;gap:0 14px}.index h3{width:100%}.index a{min-width:130px}.record{grid-template-columns:minmax(0,1fr) auto}.record p{grid-column:1/-1}}@media(max-width:640px){.topbar{align-items:flex-start;flex-direction:column}.topbar nav{gap:12px}.offline{display:none}.stats{gap:10px;flex-wrap:wrap}.stats div{min-width:62px}.map-frame svg{min-width:760px}.panel-head{align-items:flex-start;flex-direction:column}.relationship-list summary{flex-wrap:wrap}.relationship-list .relation-kind{margin-left:25px}}@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}.map-frame .node-plate,.map-frame .node-halo{transition:none}}@media print{body{background:white;color:black}.topbar,.index{display:none}.panel,.group{break-inside:avoid}details{display:block}.map-frame{overflow:visible}.map-frame svg{min-width:0}.section-head{break-after:avoid}}'
  ].join('');
  const verificationLabel = status => t(({ verified: 'Verificato', partially_verified: 'Parzialmente verificato', declared_only: 'Solo dichiarato', inferred: 'Inferito', not_verified: 'Non verificato' })[status] || 'Non verificato');
  const records = items => items.map(item => {
    const anchor = componentAnchor.get(item.id);
    return '<div class="record" id="' + anchor + '"><h3>' + esc(item.name) + '<small>' + esc(item.kind) + (item.subtype ? ' · ' + esc(item.subtype) : '') + '</small></h3><div><p>' + esc(item.description || '—') + '</p>' + (includePaths && item.path ? '<code>' + esc(item.path) + '</code>' : '') + '</div><span class="state">' + esc(verificationLabel(item.verification_status)) + '</span></div>';
  }).join('');
  const groups = sections.map((section, index) => {
    const tone = safeHex(section.tone, '#94a3b8');
    return '<details class="group" style="--tone:' + tone + '" id="group-' + index + '"' + (index < 2 ? ' open' : '') + '><summary><span class="swatch" style="--tone:' + tone + '"></span><span class="group-title">' + esc(section.name) + '</span><span class="group-count">' + section.items.length + '</span></summary><div class="records">' + (section.items.length ? records(section.items) : '<p class="empty">' + esc(t('Nessuna componente nel report.')) + '</p>') + '</div></details>';
  }).join('');
  const indexLinks = sections.filter(section => section.items.length).map(section => {
    const index = sections.indexOf(section);
    return '<a href="#group-' + index + '"><span>' + esc(section.name) + '</span><small>' + section.items.length + '</small></a>';
  }).join('');
  const toolNavigation = model.tools.map((tool, index) => '<a href="#tool-' + index + '">' + esc(tool.name) + '</a>').join('');
  const toolSections = model.tools.map((tool, index) => {
    const scope = toolScope(model, tool.id);
    const related = components.filter(item => item.id !== tool.id && scope.visibleIds.has(item.id));
    const groups = model.groups.map(group => ({ name: t(group.name), items: group.items.filter(item => scope.visibleIds.has(item.id)) })).filter(group => group.items.length);
    const outsideMap = related.filter(item => !model.groupFor.has(item.id));
    if (outsideMap.length) groups.push({ name: t('Componenti fuori mappa'), items: outsideMap });
    const groupRows = groups.map(group => '<details open><summary>' + esc(group.name) + ' · ' + group.items.length + '</summary><ul>' + group.items.map(item => '<li><a href="' + '#' + componentAnchor.get(item.id) + '">' + esc(item.name) + '</a>' + (scope.referencedIds.has(item.id) && !scope.connectedIds.has(item.id) ? '<small>' + esc(t('Citata nelle istruzioni del tool · collegamento da verificare')) + '</small>' : '') + '</li>').join('') + '</ul></details>').join('');
    return '<section class="tool-scope" id="tool-' + index + '"><h3>' + esc(tool.name) + '</h3><p>' + related.length + ' ' + esc(t('elementi')) + ' · ' + esc(t('Solo componenti nel perimetro del tool; la presenza nel workspace non prova il collegamento.')) + '</p>' + (groupRows || '<p>' + esc(t('Nessun componente collegato a questo tool.')) + '</p>') + '</section>';
  }).join('');
  const wikis = discoveredWikis(model);
  const wikiRows = wikis.map(item => '<li><a href="' + '#' + componentAnchor.get(item.id) + '">' + esc(item.name) + '</a> · ' + esc(model.linkedIds.has(item.id) ? t('Collegamento rilevato') : model.referencedIds.has(item.id) ? t('Citata nelle istruzioni del tool · collegamento da verificare') : t('Collegamento non rilevato')) + '</li>').join('');
  const wikiSection = wikis.length ? '<aside class="wiki-discovery"><h3>' + esc(t('Wiki rilevate nella scansione')) + ' · ' + wikis.length + '</h3><p>' + esc(t('La presenza della wiki non dimostra un collegamento al tool selezionato.')) + '</p><ul>' + wikiRows + '</ul></aside>' : '';
  const relationRows = relationships.map(item => {
    const sourceName = components.find(component => component.id === item.source_id)?.name || item.source_id;
    const targetName = components.find(component => component.id === item.target_id)?.name || item.target_id;
    const sourceAnchor = componentAnchor.get(item.source_id);
    const targetAnchor = componentAnchor.get(item.target_id);
    return '<li><details><summary><strong>' + esc(sourceName) + ' → ' + esc(targetName) + '</strong><span class="relation-kind">' + esc(kindLabel(relationKind(item))) + '</span></summary><div class="relation-body"><p>' + esc(item.description || '—') + '</p><span>' + esc(verificationLabel(item.verification_status)) + '</span>' + (sourceAnchor && targetAnchor ? '<p><a href="' + '#' + sourceAnchor + '">' + esc(sourceName) + '</a> → <a href="' + '#' + targetAnchor + '">' + esc(targetName) + '</a></p>' : '') + '</div></details></li>';
  }).join('');
  const legendKinds = ['contractual', 'configured', 'available', 'observed', 'structural', 'legacy_unverified'];
  const dashes = { contractual: '', configured: '10 5', available: '3 5', observed: '14 3 3 3', structural: '2 3', legacy_unverified: '8 8' };
  const legend = legendKinds.map(kind => '<span class="legend-item"><svg viewBox="0 0 30 8" aria-hidden="true"><path d="M0 4H30" fill="none" stroke="' + relationTone(kind, ink) + '" stroke-width="2" stroke-dasharray="' + dashes[kind] + '"/></svg>' + esc(kindLabel(kind)) + '</span>').join('');
  return '<!doctype html><html lang="' + esc(language) + '"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src \'none\'; style-src \'unsafe-inline\'; img-src data:; base-uri \'none\'; form-action \'none\'"><title>' + esc(report.workspace?.name) + ' · AI Setup Atlas</title><style>' + css + '</style></head><body>'
    + '<a class="skip" href="#map">' + esc(t('Vai alla mappa')) + '</a><header class="topbar"><div class="brand">AWDF <span>/</span> SETUP ATLAS</div><nav aria-label="' + esc(t('Navigazione del report')) + '"><a href="#map">' + esc(t('Mappa setup')) + '</a><a href="#inventory">' + esc(t('Componenti')) + '</a><a href="#links">' + esc(t('Collegamenti')) + '</a></nav><span class="offline">' + esc(t('Setup condiviso · consultabile offline')) + '</span></header>'
    + '<main><section class="intro"><div><p class="eyebrow">' + esc(t('Setup condiviso · consultabile offline')) + '</p><h1>' + esc(report.workspace?.name) + '</h1></div><dl class="stats"><div><dt>' + esc(t('Tool AI')) + '</dt><dd>' + model.tools.length + '</dd></div><div><dt>' + esc(t('Componenti')) + '</dt><dd>' + components.length + '</dd></div><div><dt>' + esc(t('Collegamenti')) + '</dt><dd>' + relationships.length + '</dd></div></dl></section>'
    + '<section id="map" class="panel"><div class="panel-head"><h2>' + esc(t('Mappa setup')) + '</h2><p>' + esc(t('Seleziona un nodo per aprire i suoi componenti.')) + '</p></div><div class="map-frame">' + mapSvg + '</div><div class="legend" aria-label="' + esc(t('Legenda dei collegamenti')) + '">' + legend + '</div></section><p class="note">' + esc(t('Configurazione e prescrizioni non dimostrano esecuzione o successo.')) + '</p>'
    + '<section id="tools"><div class="section-head"><h2>' + esc(t('Componenti per tool AI')) + '</h2><span>' + model.tools.length + '</span></div><p>' + esc(t('Seleziona un tool per trovare le componenti collegate.')) + '</p><nav class="tool-nav" aria-label="' + esc(t('Seleziona il tool AI da esplorare')) + '">' + toolNavigation + '</nav>' + toolSections + wikiSection + '</section>'
    + '<section id="inventory"><div class="section-head"><h2>' + esc(t('Componenti')) + '</h2><span>' + components.length + '</span></div><div class="catalog"><nav class="index" aria-label="' + esc(t('Categorie dei componenti')) + '"><h3>' + esc(t('Componenti')) + '</h3>' + indexLinks + '</nav><div class="group-list">' + groups + '</div></div></section>'
    + '<section id="links"><div class="section-head"><h2>' + esc(t('Collegamenti')) + '</h2><span>' + relationships.length + '</span></div><div class="panel"><ul class="relationship-list">' + (relationRows || '<li class="empty">' + esc(t('Nessun collegamento nel report.')) + '</li>') + '</ul></div></section><footer>' + esc(t('Configurazione e prescrizioni non dimostrano esecuzione o successo.')) + '</footer></main></body></html>';
}
