import { useEffect, useMemo, useRef, useState } from 'react';
import { CATEGORY_META, PALETTES, TYPE_TO_CATEGORY, demoReport } from './data.js';
import scannedSetupReport from '../setup-scan-report.json';

const statusLabel = { verified:'Verificata', partially_verified:'Parzialmente verificata', declared_only:'Dichiarata', inferred:'Inferita', not_verified:'Non verificata' };
const relationLabel = { uses:'usa', invoked_by:'invocato da', reads_from:'legge da', updates:'aggiorna', produces:'produce', depends_on:'dipende da', configured_by:'configurato da', references:'riferisce' };
const clean = (value) => typeof value === 'string' ? value.replace(/<[^>]*>/g, '') : value;
const categoryOf = (component) => TYPE_TO_CATEGORY[component.type] || 'other';

function validateReport(value) {
  if (!value || typeof value !== 'object') throw new Error('Il file non contiene un oggetto JSON.');
  if (!value.schema_version) throw new Error('Manca il campo obbligatorio “schema_version”.');
  if (!Array.isArray(value.components)) throw new Error('“components” deve essere un array.');
  if (value.relationships !== undefined && !Array.isArray(value.relationships)) throw new Error('“relationships” deve essere un array.');
  const ids = new Set(value.components.map(x => x.id));
  const invalid = (value.relationships || []).find(x => !ids.has(x.source_id) || !ids.has(x.target_id));
  if (invalid) throw new Error(`La relazione “${invalid.id || 'senza id'}” riferisce un componente inesistente.`);
  return { ...value, relationships:value.relationships || [], findings:value.findings || [], evidence:value.evidence || [], warnings:value.warnings || [] };
}

function centralTool(report) {
  return report.components.map(item => {
    const edges = report.relationships.filter(r => r.source_id === item.id || r.target_id === item.id);
    const related = edges.map(r => report.components.find(c => c.id === (r.source_id === item.id ? r.target_id : r.source_id)));
    const score = edges.length * 1.1 + related.filter(c => categoryOf(c) === 'agents' || categoryOf(c) === 'skills').length * 1.5 + (['tool','model','application'].includes(item.type) ? 4 : 0) + (/main|primary|centrale|codex/i.test(`${item.name} ${item.description || ''}`) ? 5 : 0);
    return {item,score};
  }).sort((a,b) => b.score-a.score)[0]?.item || null;
}

function App() {
  const [report, setReport] = useState(() => {
    try { return validateReport(scannedSetupReport); }
    catch { return demoReport; }
  }), [paletteId, setPaletteId] = useState(() => localStorage.getItem('setup-visualizer:palette:v1') || 'dark');
  const [palette, setPalette] = useState(() => PALETTES[localStorage.getItem('setup-visualizer:palette:v1')] || PALETTES.dark);
  const [selectedCategory, setSelectedCategory] = useState(null), [selectedId, setSelectedId] = useState(null), [selectedEdge, setSelectedEdge] = useState(null);
  const [expanded, setExpanded] = useState(new Set()), [query,setQuery] = useState(''), [minConfidence,setMinConfidence] = useState(0), [showFindings,setShowFindings] = useState(false), [paletteOpen,setPaletteOpen] = useState(false), [notice,setNotice] = useState('');
  const inputRef=useRef();
  useEffect(() => { localStorage.setItem('setup-visualizer:palette:v1',paletteId); }, [paletteId]);
  const central = useMemo(() => centralTool(report),[report]);
  const findingsFor=(id) => report.findings.filter(f => f.component_id===id || f.component_ids?.includes(id));
  const categories = useMemo(() => Object.entries(CATEGORY_META).map(([id,meta]) => ({id,...meta,items:report.components.filter(c=>categoryOf(c)===id)})).filter(c=>c.items.length),[report]);
  const filteredCategories = categories.map(cat=>({...cat,items:cat.items.filter(x => x.confidence === undefined || x.confidence >= minConfidence).filter(x => !query || JSON.stringify(x).toLowerCase().includes(query.toLowerCase()))})).filter(c=>c.items.length || !query);
  const selected = report.components.find(c=>c.id===selectedId);
  const displayItems = selectedCategory ? (categories.find(c=>c.id===selectedCategory)?.items || []) : [];
  const chooseCategory=(id)=>{setSelectedCategory(id);setSelectedId(null);setSelectedEdge(null);setExpanded(prev=>new Set([...prev,id]));};
  const importFile=(event)=>{ const file=event.target.files?.[0]; if(!file) return; if(!file.name.toLowerCase().endsWith('.json')) {setNotice('Seleziona un file con estensione .json.');return;} if(file.size > 10*1024*1024){setNotice('Il file supera il limite di 10 MB.');return;} const reader=new FileReader();reader.onload=()=>{try {setReport(validateReport(JSON.parse(reader.result)));setSelectedCategory(null);setSelectedId(null);setNotice(`Report “${file.name}” caricato localmente.`)} catch(e){setNotice(`Import non riuscito: ${e.message}`)}}; reader.readAsText(file); event.target.value=''; };
  const updateColor=(category,value)=> setPalette(p=>({...p,categories:{...p.categories,[category]:value}}));
  const resetPalette=()=>{setPalette(PALETTES[paletteId]);setNotice('Palette ripristinata.');};
  const nodeFor=(component) => { const cat=categoryOf(component); return <button key={component.id} className="component-node" style={{'--node':palette.categories[cat]}} onClick={()=>{setSelectedId(component.id);setSelectedCategory(cat);setSelectedEdge(null)}} aria-label={`Apri ${component.name}`}><span className="node-dot"/><span>{component.name}</span>{findingsFor(component.id).length>0 && <b className="finding-badge">!</b>}</button>};
  return <main className={`app ${palette.mode}`} style={{'--canvas':palette.canvas.background,'--grid':palette.canvas.grid,'--ink':palette.centralTool.text,'--central':palette.centralTool.background,'--central-border':palette.centralTool.border,'--selection':palette.canvas.selection}}>
    <header><div className="brand"><div className="logo">◌</div><div><strong>Setup Visualizer</strong><span>{clean(report.report?.name) || 'Report AI setup'}</span></div></div><div className="header-actions"><button onClick={()=>inputRef.current.click()}>↑ Importa JSON</button><input ref={inputRef} type="file" accept="application/json,.json" onChange={importFile} hidden/><button className="ghost" onClick={()=>setShowFindings(!showFindings)}>⚑ Findings <em>{report.findings.length}</em></button><button className="ghost" onClick={()=>setPaletteOpen(true)}>◐ Palette</button></div></header>
    {notice && <div className="notice" role="status">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
    <section className="workspace">
      <aside className="sidebar"><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Cerca componenti"/></label><section><div className="side-title"><span>CATEGORIE</span><b>{report.components.length}</b></div><div className="category-list">{filteredCategories.map(cat=><button key={cat.id} className={selectedCategory===cat.id?'active':''} onClick={()=>chooseCategory(cat.id)}><i style={{color:palette.categories[cat.id],background:`${palette.categories[cat.id]}22`}}>{cat.icon}</i><span>{cat.label}</span><b>{cat.items.length}</b></button>)}</div></section><section className="filters"><div className="side-title"><span>FILTRI</span><button onClick={()=>{setQuery('');setMinConfidence(0)}}>Reset</button></div><label>Confidenza minima <output>{Math.round(minConfidence*100)}%</output><input type="range" min="0" max="1" step=".1" value={minConfidence} onChange={e=>setMinConfidence(+e.target.value)}/></label></section><section className="legend"><div className="side-title"><span>LEGENDA RELAZIONI</span></div><p><i className="line solid"/> verificata</p><p><i className="line dashed"/> dichiarata</p><p><i className="line dotted"/> inferita</p></section></aside>
      <section className="graph-wrap"><div className="graph-toolbar"><span>Overview radiale</span><div><button onClick={()=>setExpanded(new Set())}>Comprimi</button><button onClick={()=>setExpanded(new Set(categories.map(x=>x.id)))}>Espandi</button></div></div><div className="graph" aria-label="Grafo del setup AI"><svg className="edges" viewBox="0 0 1000 680" preserveAspectRatio="none" aria-hidden="true">{categories.map((cat,i)=>{const a=(Math.PI*2*i/categories.length)-Math.PI/2;return <line key={cat.id} x1="500" y1="340" x2={500+265*Math.cos(a)} y2={340+205*Math.sin(a)} stroke={palette.categories[cat.id]} strokeOpacity=".45" strokeWidth="2"/>})}</svg><div className="central-node" style={{borderColor:palette.centralTool.border}}><span className="central-icon">✦</span><strong>{central?.name || 'Setup AI'}</strong><small>Tool AI principale</small><footer><span>↔ {report.relationships.filter(r=>r.source_id===central?.id||r.target_id===central?.id).length} connessioni</span><span>● {central?.maturity || central?.status || 'Rilevato'}</span></footer></div>{categories.map((cat,index)=>{const angle=360*index/categories.length-90; const x=50+38*Math.cos(angle*Math.PI/180), y=50+34*Math.sin(angle*Math.PI/180);return <div key={cat.id} className="radial-group" style={{left:`${x}%`,top:`${y}%`}}><button className={`category-node ${selectedCategory===cat.id?'selected':''}`} style={{'--node':palette.categories[cat.id]}} onClick={()=>chooseCategory(cat.id)}><i>{cat.icon}</i><strong>{cat.label}</strong><span>{cat.items.length} elementi</span>{cat.items.some(c=>findingsFor(c.id).length) && <b className="risk-dot"/>}</button>{expanded.has(cat.id)&&<div className="orbit-items">{cat.items.slice(0,4).map(nodeFor)}{cat.items.length>4&&<button className="more" onClick={()=>chooseCategory(cat.id)}>+{cat.items.length-4} altri</button>}</div>}</div>})}</div><div className="graph-footer"><span>{report.components.length} elementi</span><span>{report.relationships.length} relazioni</span><span className="warning">△ {report.warnings.length} warning</span><span>⌘ trascina · +/− zoom</span></div></section>
      <aside className="details">{showFindings ? <Findings findings={report.findings} components={report.components} palette={palette} onSelect={(id)=>{setSelectedId(id);setShowFindings(false)}}/> : selected ? <Detail component={selected} report={report} palette={palette} onNode={id=>setSelectedId(id)} /> : selectedCategory ? <CategoryPanel category={categories.find(x=>x.id===selectedCategory)} palette={palette} findingsFor={findingsFor} onSelect={setSelectedId}/> : <Overview report={report} central={central} categories={categories} palette={palette} />}</aside>
    </section>
    {paletteOpen && <PaletteModal palette={palette} paletteId={paletteId} setPaletteId={id=>{setPaletteId(id);setPalette(PALETTES[id])}} updateColor={updateColor} reset={resetPalette} close={()=>setPaletteOpen(false)}/>}
  </main>
}

function Overview({report,central,categories,palette}) {return <div className="panel overview"><p className="eyebrow">SETUP OVERVIEW</p><h2>{central?.name || 'Tool centrale non identificato'}</h2><p>{clean(central?.description) || 'Seleziona un componente come focus del setup.'}</p><div className="metric-grid"><div><strong>{report.components.length}</strong><span>elementi</span></div><div><strong>{report.relationships.length}</strong><span>relazioni</span></div><div><strong>{report.findings.length}</strong><span>finding</span></div></div><h3>Composizione</h3>{categories.map(c=><div className="bar-row" key={c.id}><span>{c.label}</span><div><i style={{width:`${(c.items.length/report.components.length)*100}%`,background:palette.categories[c.id]}}/></div><b>{c.items.length}</b></div>)}<div className="privacy">⌂ I dati vengono elaborati nel browser e non vengono inviati all'esterno.</div></div>}
function CategoryPanel({category,palette,findingsFor,onSelect}) {return <div className="panel"><p className="eyebrow" style={{color:palette.categories[category.id]}}>{category.icon} CATEGORIA</p><h2>{category.label}</h2><p>{category.description}</p><div className="panel-stat"><strong>{category.items.length}</strong> elementi rilevati</div><div className="item-list">{category.items.map(item=><button key={item.id} onClick={()=>onSelect(item.id)}><i style={{background:palette.categories[category.id]}}/><span><strong>{item.name}</strong><small>{item.type} · {Math.round((item.confidence||0)*100)}% confidence</small></span>{findingsFor(item.id).length>0&&<b>!</b>}<em>›</em></button>)}</div></div>}
function Detail({component,report,palette,onNode}) { const related=report.relationships.filter(r=>r.source_id===component.id||r.target_id===component.id);const findings=report.findings.filter(f=>f.component_id===component.id); const cat=categoryOf(component); return <div className="panel detail"><p className="eyebrow" style={{color:palette.categories[cat]}}>{CATEGORY_META[cat].icon} {component.type}</p><h2>{component.name}</h2><div className="chips"><span>{component.status||'unknown'}</span><span>◒ {Math.round((component.confidence||0)*100)}%</span></div><p>{clean(component.description)||'Nessuna descrizione disponibile.'}</p><h3>Connessioni <b>{related.length}</b></h3><div className="connections">{related.map(r=>{const other=report.components.find(c=>c.id===(r.source_id===component.id?r.target_id:r.source_id));return <button key={r.id} onClick={()=>onNode(other.id)}><span><i className={`line ${r.verification_status==='inferred'?'dotted':r.verification_status==='verified'?'solid':'dashed'}`}/>{relationLabel[r.type]||r.type}</span><strong>{other?.name||'Elemento rimosso'} ›</strong><small>{statusLabel[r.verification_status]||r.verification_status} · {Math.round((r.confidence||0)*100)}%</small></button>})}</div>{findings.length>0&&<><h3>Findings</h3>{findings.map(f=><div className="finding" key={f.id} style={{borderColor:palette.severity[f.severity]}}><b style={{color:palette.severity[f.severity]}}>{f.severity}</b><strong>{f.title}</strong><p>{f.recommendation}</p></div>)}</>}<details><summary>Raw data</summary><pre>{JSON.stringify(component,null,2)}</pre></details></div>}
function Findings({findings,components,palette,onSelect}) {return <div className="panel"><p className="eyebrow">⚑ FINDINGS</p><h2>Priorità di intervento</h2><p>Le criticità vengono sempre accompagnate da confidence e raccomandazione.</p><div className="finding-list">{findings.map(f=>{const component=components.find(c=>c.id===f.component_id);return <button key={f.id} className="finding" style={{borderColor:palette.severity[f.severity]}} onClick={()=>onSelect(f.component_id)}><b style={{color:palette.severity[f.severity]}}>{f.severity}</b><strong>{f.title}</strong><span>{component?.name}</span><p>{f.recommendation}</p></button>})}</div></div>}
function PaletteModal({palette,paletteId,setPaletteId,updateColor,reset,close}) {return <div className="modal-backdrop" role="dialog" aria-modal="true"><section className="palette-modal"><header><div><p className="eyebrow">PERSONALIZZAZIONE</p><h2>Palette colori</h2></div><button onClick={close}>×</button></header><p>Le modifiche sono visualizzate subito e la palette selezionata viene ricordata localmente.</p><div className="preset-row">{Object.values(PALETTES).map(p=><button className={paletteId===p.id?'active':''} key={p.id} onClick={()=>setPaletteId(p.id)}>{p.name}</button>)}</div><h3>Categorie</h3><div className="color-grid">{Object.entries(CATEGORY_META).map(([id,meta])=><label key={id}><span>{meta.icon} {meta.label}</span><input type="color" value={palette.categories[id]} onChange={e=>updateColor(id,e.target.value)}/><code>{palette.categories[id]}</code></label>)}</div><footer><button className="ghost" onClick={reset}>Ripristina</button><button onClick={close}>Fine</button></footer></section></div>}
export default App;
